STATUS_ORDER_IN_WAITING = "в ожидании"
STATUS_ORDER_PAYMENT_OK = "оплачено"
STATUS_ORDER_COMPLETE = "готово"

TAG_NAME_HTML_NEW_ORDER_LIST_ITEMS = "data_for_order"
TAG_NAME_HTML_NEW_ORDER_TABLE_NUMBER = "table_number_for_order"
TAG_NAME_HTML_ID_ORDER = "id"

SYMBOL_SPLIT_TO_ROWS = "\n"
SYMBOL_SPLIT_TO_NAME_PRICE = "' "

SYMBOL_JOIN_TITLES_ITEMS = ", "