# Generated by Django 5.1.7 on 2025-03-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='count',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
