# Generated by Django 5.1.7 on 2025-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_item_count_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='в ожидании', max_length=10),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
